apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      version: "6.7.0" # {"$imagepolicy": "flux-system:podinfo:tag"}
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.production
          paths:
            - path: /
              pathType: ImplementationSpecific
