---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-podinfo
  labels:
    app.kubernetes.io/name: microservices-podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microservices-podinfo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservices-podinfo
    spec:
      serviceAccountName: microservices-podinfo
      automountServiceAccountToken: true
      containers:
        - name: microservices-podinfo
          image: stefanprodan/podinfo:6.7.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: microservices-podinfo
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-podinfo
data:
  MY_ENV: "MyValue"
