image: atlassian/default-image:3

pipelines:
  custom:
    pr-promotion:
      - variables:
          - name: KIND
          - name: NAME
          - name: NAMESPACE
          - name: REVISION
          - name: SEVERITY
          - name: REASON
          - name: MESSAGE
      - step:
          name: check and bump version
          script:
            - echo "KIND: $KIND"
            - echo "NAME: $NAME"
            - echo "NAMESPACE: $NAMESPACE"
            - echo "REVISION: $REVISION"
            - echo "SEVERITY: $SEVERITY"
            - echo "REASON: $REASON"
            - echo "MESSAGE: $MESSAGE"
