apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/microservices
patches:
  - path: microservices-patch.yaml
    target:
      kind: Deployment
      name: microservices-podinfo



